Home page banner/landing section #310
Nonprofit-Exchange-Hub/web-app pull request #316
Opened 2023-04-07 03:25 UTC by taoliu12

issue [#310](https://github.com/Nonprofit-Exchange-Hub/web-app/issues/310) 

Done, as I showed during our team meeting.

2023-04-09 02:43 UTC, taoliu12 commented
Still need to fix eslint errors. Holding off on merging until I fix the eslint errors.

2023-04-09 17:48 UTC, taoliu12 commented
fixed eslint errors. Should be ready to merge now.

2023-04-14 00:39 UTC, esteban-gs requested changes
See comments

2023-04-25 00:03 UTC, taoliu12 commented
@esteban-gs Refactored as much as it currently make sense to me. 
Should be ready to merge, but also let me know if you need anything else.

2023-04-26 03:18 UTC, esteban-gs commented on client/src/components/BannerSection.tsx
> +            <CTAButton text="Join Now" />
✅

2023-04-26 03:20 UTC, esteban-gs approved these changes
Looks good to me! 🚀

2023-04-26 06:15 UTC, merged