add email_verified: true
Nonprofit-Exchange-Hub/web-app pull request #318
Opened 2023-04-09 17:43 UTC by taoliu12

added "email_verified: true," to both seed users, and Login works correctly now.

2023-04-11 01:50 UTC, esteban-gs requested changes
Nice! this should get us closer to closing this issue. A couple of changes in comments and here:

- At one point we added the `email_verified` property back to the `create-user-dto.ts` class. This should be reverted. Even though the card doesn't require if explicitly, we could benefit from fixing this. 
- Requested changes:
  - Remove the `email_verified?` property from `create-user.dto` - `src/acccount-manager/dto/create-user.dto.ts`
  - In the seed date. use the `CreateUserInternal` - `src/acccount-manager/dto/create-user.internal.ts` type instead of `CreateUserDto`. 

The main idea behind this is to disallow the controller's ability to update the `email_verified` field, since it controls access to the app. Internally, we can still override it by using the service type `CreateUserInternal` which has access to that property.

2023-04-14 04:41 UTC, taoliu12 commented on server/src/acccount-manager/dto/create-user.dto.ts
Sorry, not sure why the entire file is diff'ed.
But I removed the 
`  @IsBoolean()
  email_verified?: boolean;`

2023-04-14 04:49 UTC, taoliu12 commented
@esteban-gs I made the requested changes, and re-seeded to make sure login still works.  

Also, sorry, not sure why the entire file is diff'ed .
But I removed the email_verified? property from create-user.dto

2023-04-16 19:18 UTC, esteban-gs approved these changes
Looks good to me!

2023-04-17 19:20 UTC, merged