Add to swagger API documentation
Nonprofit-Exchange-Hub/web-app pull request #336
Opened 2023-05-04 18:08 UTC by marvinsjsu

## Dev Summary

[Mocks](link)

## Test Plan

repro steps:

1. localhost:3000 
2. click X button
expected: 

## Resources

- [stackoverflow is cool](stackoverflow.com)

2023-05-06 00:41 UTC, esteban-gs requested changes
@marvinsjsu , thanks or working on this! Looking good so far. I don't see anything incorrect with your changes, but with how you approached this, I think it would be a good opportunity to decide on one way of getting OpenApi to generate our Api docs.

There are 2 approaches to to decide from.
- Rely on nestjs auto-annotate plugin (my personal preference), it requires a heavy use of `.dto.ts` classes and keep the `@Api...` annotations to a minimum. A downside of this is that we have to duplicate the return type properties, but this might scale better if when we make a heavier use of `class-transformer` if we ever do any formatting before sending to the client. I think the card left out that we set up OpenApi to auto-annotate on app build and it will pick up any files with the .dto suffix, so really, we don't need these annotations in the dtos.

You can see where we configure this auto-annotate feature in nest-cli.json.

- Annotate each entity field and each controller method. This is a more manual approach, and requires a lot of annotations, but it does remove the need to create a `.dto.ts` return type

2023-05-12 20:13 UTC, marvinsjsu commented on server/src/acccount-manager/account-manager.controller.ts
> +  })
Thanks for pointing these out.  I also prefer letting the auto annotation plugin handle the work as it was pretty tedious to do this manually.

2023-05-28 19:22 UTC, esteban-gs requested changes
@marvinsjsu Thank you for  working on this. Looks good. I have one comment so far where we can concretely remove annotations

2023-05-28 19:22 UTC, esteban-gs commented on server/src/acccount-manager/dto/create-user.dto.ts
> +  @ApiProperty()
In this dto file, we can remove all the `@ApiProperty()` annotations from `@nestjs/swagger`. The OpenApi plugin will pick up the required/optional properties as well as the interest type based on the typescript types.

2023-05-29 23:17 UTC, esteban-gs commented on server/src/acccount-manager/entities/user.entity.ts
@marvinsjsu , we can also remove all instances of `User` as the return type in `account-manager.controler.ts` and user the existing `ReturnUserDto` class instead as a return type. 

Once you do that, you can remove all the OpenApi annotations from this class.

2023-05-29 23:19 UTC, esteban-gs commented on server/src/assets/dto/create-asset.dto.ts
You can also remove all the instances of `@ApiProperty()` and `@ApiPropertyOptional()` from this dto since the OpenApi can infer this from the types and the `foo?: string` optional property operator.

2023-05-29 23:22 UTC, esteban-gs commented on server/src/assets/dto/get-asset.dto.ts
You can safely remove the annotations here as well.

2023-05-29 23:25 UTC, esteban-gs commented on server/src/assets/entities/asset.entity.ts
Instead of annotating this entity, we should create a new class following the dto convention, similar to `ReturnUserDto`. Inheriting from this class won't work for auto-documenting, so you'll have to declare the same properties as this class. We can trade off auto-documentation for code repetition.

2023-06-02 00:10 UTC, esteban-gs commented on server/src/categories/dto/create-category.dto.ts
@marvinsjsu , the annotations here can be removed as well

2023-06-02 00:16 UTC, esteban-gs commented on server/src/categories/dto/get-categories-filter.dto.ts
Instead of extending from the `CreateCategoryDto` let's declare the properties here even if they are duplicated, This will also be useful when we use `class-transformer`.

This way, dtos can be the place where we deal with class-transformations and return types and it's decoupled from entities.

2023-06-02 00:35 UTC, esteban-gs commented on server/src/categories/entities/category.entity.ts
>    id: number;
You can get the same behavior by removing the annotation and adding the optional property denotator:

```suggestion
  @PrimaryGeneratedColumn()
  id: number?;
```

2023-06-02 00:37 UTC, esteban-gs commented on server/src/categories/dto/create-category.dto.ts
>    applies_to_organizations: boolean;
You can get the same behavior by removing the annotation and adding the optional property denotator:

```suggestion
  @IsOptional()
  applies_to_assets?: boolean;

  @IsOptional()
  applies_to_organizations?: boolean;
```

2023-06-04 21:42 UTC, marvinsjsu commented
@esteban-gs, sorry it took me some time to get back to working on this. Hope the changes align to a better approach, and thank you for your patience on this.

2023-06-09 00:56 UTC, esteban-gs commented on server/src/assets/dto/return-asset.dto.ts
👍🏾

2023-06-09 00:58 UTC, esteban-gs requested changes

2023-06-09 00:58 UTC, esteban-gs commented on server/src/acccount-manager/entities/user.entity.ts
> +  @ApiProperty()
@marvinsjsu , these can be removed as well

2023-06-09 00:58 UTC, esteban-gs commented on server/src/acccount-manager/dto/create-user.dto.ts
> +  @ApiProperty()
These can be removed

2023-06-09 00:58 UTC, esteban-gs commented
@marvinsjsu  looking good! Thanks for working through those changes.

2023-06-23 00:39 UTC, esteban-gs approved these changes
@marvinsjsu , thanks for working though these changes

2023-06-23 19:23 UTC, marvinsjsu commented
@esteban-gs, I very much appreciate your patience on this and the follow-up PR.

2023-06-24 19:11 UTC, merged