Home page how it works section #311
Nonprofit-Exchange-Hub/web-app pull request #349
Opened 2023-06-12 18:52 UTC by taoliu12

How it works card section completed.

## Dev Summary

[Mocks](link)

## Test Plan

repro steps:

1. localhost:3000 
2. click X button
expected: 

## Resources

- [stackoverflow is cool](stackoverflow.com)

2023-06-13 02:46 UTC, esteban-gs requested changes
@taoliu12 , thanks for working on this. I just have a couple of recommendations.

Also, the build is failing, but not due to your code. I think if we drop the `--legacy-peer-deps` from the line [here](https://github.com/Nonprofit-Exchange-Hub/web-app/blob/318a504a5f4bea6cdeef6ecaca63c6b0e795f443/Dockerfile#L8), it will build successfully.

2023-06-13 02:46 UTC, esteban-gs commented on client/src/views/HowItWorks.tsx
> +    image: HowItworks1,
I think we could enhance readability by renaming all these images to what they do, for example: `sign-up-with-givingful.svg`

2023-06-13 02:46 UTC, esteban-gs commented on client/src/views/HowItWorksCards.tsx
Both this and the `HowItWorksCard` component can go in the components directory. We are reserving `src/views` for top-level page views.

2023-06-13 03:13 UTC, esteban-gs commented on client/src/views/HowItWorksCard.tsx
> +/* eslint-disable prettier/prettier */
@taoliu12 , it seems like this eslint comment is causing the build to break.
```suggestion

```

2023-06-20 20:29 UTC, taoliu12 commented on client/src/views/HowItWorks.tsx
> +import PeopleFlag from '../assets/HowItWorks/people-flag.svg';
these are the new SVG names

2023-06-21 04:22 UTC, esteban-gs approved these changes
Looks good to me!

2023-06-21 18:17 UTC, merged