343 add validation to user signup form
Nonprofit-Exchange-Hub/web-app pull request #363
Opened 2023-08-02 19:08 UTC by marvinsjsu

## Dev Summary

[Mocks](link)

## Test Plan

repro steps:

1. localhost:3000 
2. click X button
expected: 

## Resources

- [stackoverflow is cool](stackoverflow.com)

2023-08-02 19:38 UTC, marvinsjsu commented on client/src/components/Users/Auth/SignUpCitizen/StepOne.tsx
> +    initialFormData[key].value = initData[key];
I've used `// @ts-ignore` on multiple lines as an escape hatch as I'm not sure how to get this to work with TypeScript.  If you guys have any ideas on how I could/should do this, that'd be awesome.

2023-08-03 07:25 UTC, EtoKruto commented
Regarding Passwords in the Video:

See video - I noticed that going back to the first password may still allow proceeding. Though this might be a minor correction since it's not typical user behavior, I thought it might be worth looking into. Nice work, looks clean


https://github.com/Nonprofit-Exchange-Hub/web-app/assets/92830192/ea5e0c49-d39e-412d-bb52-c32c37375886

2023-08-03 07:26 UTC, EtoKruto commented
On Titles and Styles:
I observed that the purple titles on each page don't exactly match the styles, but I like the direction you've taken with this, looks to be an improvement on the mock UI so I say keep it

2023-08-03 07:28 UTC, EtoKruto commented
Console Log Clean-Up:
Once ready, clean up any console.log entries

2023-08-04 21:40 UTC, esteban-gs requested changes
@marvinsjsu , thanks for working on this. If we want to use redux going forward, we'll probably need to update other forms and remove other libraries (probably for another PR).

2023-08-04 21:40 UTC, esteban-gs commented on client/package.json
> +		"@reduxjs/toolkit": "^1.9.5",
@marvinsjsu , do we want to settle on `redux` without any other form library? If so, we'll also want to add some cards to remove `react-query` and `react-hooks-form`. There are a few forms (signupnonprofit) using it. I like Redux' separation of concerns, but one downside is all the boilerplate.

Either way, I'm down with it.

2023-08-04 21:40 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/StepOne.tsx
> +          sx={{ color: '#674E67' }}
For all the places where we set the color, we could use the existing theme colors, or add this color to the theme if it's new.

2023-08-04 21:40 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/StepOne.tsx
> +          style={{
If `sx={..` work for this MUI component, we should use it instead of style, I think.

2023-08-04 21:40 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/StepOne.tsx
> +          fontSize="22px"
I think it might be better to set these in `typography.ts`, maybe set a form input variant.

2023-09-06 21:45 UTC, marvinsjsu commented
hi @esteban-gs and @EtoKruto, I've updated this PR based on the feedback, but I'm going to work on the styling in the other ticket I have - https://github.com/orgs/Nonprofit-Exchange-Hub/projects/14?pane=issue&itemId=33617416 (since this PR is getting kinda big and the other ticket is more for styling changes anyways).  I think it's ready for another look.  Thanks guys!

2023-09-08 05:43 UTC, esteban-gs requested changes
@marvinsjsu , thank you for tackling this! I think we are getting close to being ready. I left a couple of comments and one blocking comment about the last step not working as intended.

2023-09-08 05:43 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/StepFour.tsx
> +          </Button>
Step 4 data (bio) isn't getting merged with the rest of the data. Maybe you need to call the `handleNext` parent method as well.

2023-09-08 05:43 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/StepOne.tsx
> +  });
I think we should leave this query out of this iteration until we define this further. What do you think?

2023-09-08 05:43 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/StepThree.tsx
> +      // TODO: toggle chip style when interest is chosen
```suggestion
```

2023-09-08 05:43 UTC, esteban-gs commented on server/src/acccount-manager/account-manager.controller.ts
> +
My suggestion is to leave this new public endpoint out of this PR until we solve this issue further.

```suggestion
```

2023-09-10 01:53 UTC, marvinsjsu commented
@esteban, thanks for catching the bug with `bio`.  This should be fixed now and I've also removed the email check.

2023-09-10 04:32 UTC, esteban-gs approved these changes
There is one linting rule exception comment that's tripping up the build. LGTM after that's addressed 🚢

2023-09-10 04:32 UTC, esteban-gs commented on client/src/components/Users/Auth/SignUpCitizen/SignUpCitizen.tsx
> +      : setActiveStep((prevActiveStep) => prevActiveStep + 1);
prettier doesn't like this in-line warning disabling comment. See the build errors.

You should be able to just format it in a single line to get rid of the lint warning.

```suggestion
doSubmit ? setSubmitForm(true) : setActiveStep((prevActiveStep) => prevActiveStep + 1);
```

2023-09-11 00:29 UTC, merged

2023-09-11 21:05 UTC, garimacha commented
@marvinsjsu This PR is under review but its not under the In progress vertical. Shouldn't this be moved under in progress?