Create needs and needs/goods form
Nonprofit-Exchange-Hub/web-app pull request #39
Opened 2021-09-24 00:32 UTC by nstjean

I've created the Need-Initiate form at /need/
![FireShot Capture 292 - Nonprofit Exchange Hub - localhost](https://user-images.githubusercontent.com/49460529/134598986-ba6e5329-8041-4936-8500-a80e16adb9de.png)

And then the Need-Goods form at /need/goods/
![FireShot Capture 294 - Nonprofit Exchange Hub - localhost](https://user-images.githubusercontent.com/49460529/134599039-82d30397-d3a0-4e66-92ad-d08461359dc5.png)

I've tried to keep all the logic for the form in NeedFormGoods, with custom components for the TextField, Select, Radio and FileUpload. Hopefully now I can make the other forms pretty quickly. :)

Later I'm going to try to pull the styling out of NeedFormGoods into the theme, if possible.

2021-09-28 00:11 UTC, jd2rogers2 requested changes

2021-09-28 00:11 UTC, jd2rogers2 commented on client/src/NeedFormGoods.tsx
> +    const handleChange = (evt: React.ChangeEvent<HTMLInputElement>): void => {
got TS here on compile
for the typing of this function and where it's used down the pipeline
let's just follow MUI docs https://v4.mui.com/components/selects/ for now (despite the `unknown`)
(see one of the snippets and then select TS)

2021-09-28 00:11 UTC, jd2rogers2 commented on client/src/Helpers/index.ts
> +export { default as setDefaults } from './setDefault';
i think this whole file and folder need to be deleted

2021-09-28 00:11 UTC, jd2rogers2 commented on client/src/NeedFormGoods.tsx
> +                    <Grid container spacing={5} className={classes.grid}>
error on compile here too, no `grid` key in the classes obj

2021-10-06 18:20 UTC, nstjean commented on client/src/FormElements/CustomSelect.tsx
> +    }[],
Sounds fun. I'll try it out!

2021-10-07 11:29 UTC, jd2rogers2 commented on client/src/NeedFormGoods.tsx
> +                                <Button variant='contained' color='secondary'>
haha i guess so, not sure really. i just know that everyone does it

2021-10-07 11:52 UTC, jd2rogers2 approved these changes
one more piece of clean up then 🚀

2021-10-07 11:52 UTC, jd2rogers2 commented on client/src/FormElements/Select.tsx
> +const handleChange = (event: React.ChangeEvent<{ name?: string | undefined; value: unknown; }>): void => {
not being used, remove

2021-10-07 20:41 UTC, merged